import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import Head from 'next/head'
import { Features, Header, Hero, Download, Pricing, Clients, Services, Contact, Footer } from "@/layouts";
import { Suspense } from 'react';
import Loading from './loading';

export default function Home() {
  return (
    <>
      <Head>
        <title>SmartHotel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </Head>
      <Suspense fallback={<Loading/>}>
        <Header />
        <Hero />
        <Features />
        <Download />
        <Pricing />
        <Services />
        <Clients />
        <Contact />
        <Footer />
      </Suspense>
    </>
  )
};


export async function getStaticProps({ locale }: any) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common']))
    },
  }
}